# Shell
set -g default-command "pwsh -NoLogo"

set -g default-path "$HOME"

# Terminal & colors
set -a terminal-features "tmux-256color:RGB"

# Prefix
set -g prefix C-SPACE

set -g base-index 1
set -g renumber-windows on

# Top bar, centered, minimalistic
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=#000000,fg=default"
set -g status-left-style "bg=default,fg=default"
set -g status-right-style "bg=default,fg=default"
set -g message-style "bg=default,fg=default"
set -g pane-border-style "fg=colour240"
set -g pane-active-border-style "fg=colour252"
set -g window-status-style "bg=default,fg=default"

# Tabs
set -g window-status-separator ""
set -g window-status-format         "#[fg=colour240,bg=default] #I:#W#{?window_flags,#{window_flags},} #[default]"
set -g window-status-current-format "#[fg=colour252,bg=default,bold] #I:#W#{?window_flags,#{window_flags},} #[default]"

# Sides of the bar
set -g status-left "#[fg=colour240,bg=default]#S#[default]"
set -g status-right ""
set -g status-interval 5

#Binds
bind x kill-window
